# Generated by Django 3.0.8 on 2020-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=45)),
                ('content', models.TextField()),
            ],
        ),
    ]
